### ISSUE TITLE
Error, no test specified

### ISSUE THREAD

**Issue by TamTamThomas** [jpott77/webdriverio#3]
Hello,

I am new to testing and currently doing the Applitools course and facing with the below error message.

"Error: no test specified"
npm ERR! code ELIFECYCLE
npm ERR! errno 1

this is my "element.test.js" in my "test" folder in the root folder:
describe("Interacting with elements", function() {
    it("Get text for element", () => {
        browser.url('/')
        let text = $("h2").getText()
        console.log(text)
    })
})

in package.json:
"scripts": {
    "test": "node ./node_modules/.bin/wdio ./wdio.conf.js"
  },

in wdio.conf.js:
specs: [
        './test/**/*.js'
    ],

but the full result if npm run test is:
PS C:\Users\xxx\Documents\WebdriverIO Tutorial> npm run test

> webdriverio-tutorial@1.0.0 test C:\Users\xxx\Documents\WebdriverIO Tutorial
> echo "Error: no test specified" && exit 1

"Error: no test specified"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio-tutorial@1.0.0 test: `echo "Error: no test specified" && exit 1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriverio-tutorial@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-04-29T10_34_46_706Z-debug.log

What am I doing wrong?

Thank you for any help.

Tam

**Comment by jpott77** [comment]
Hey @TamTamThomas can you create repo with what you have so that I can take a look at it?

**Comment by TamTamThomas** [comment]
Hi Julia,

Thank you for your help.

I have uploaded a repository, but really not sure if this is the way I supposed to do it.

https://github.com/TamTamThomas/WDIO-error

Thank you for your time.

Tam

**Comment by jpott77** [comment]
I pulled down your project and did an npm install and then an npm run test and it passed without me changing anything.

Can you update your test script to be `./node_modules/.bin/wdio ./wdio.conf.js` instead of `node ./node_modules/.bin/wdio ./wdio.conf.js`

Let me know if that works

**Comment by TamTamThomas** [comment]
Hi Julia,

It works, thanks. Why this happened?

Thank you.

Kind regards,
Tom

**Comment by jpott77** [comment]
Its an issue that you may experience if you are using Windows. The command would need to be different than on other systems

**Comment by thocego** [comment]
Buen día @jpott77, me sucede lo mismo! :(
![image](https://user-images.githubusercontent.com/76695279/108228548-f6420480-710c-11eb-97d9-b564467a5d01.png)

**Comment by saamorin** [comment]
> Buen día @jpott77, me sucede lo mismo! :(
> ![image](https://user-images.githubusercontent.com/76695279/108228548-f6420480-710c-11eb-97d9-b564467a5d01.png)

Hola!
A mí me funcionó la solución de Julia. 

Actualizar en package.json lo siguiente:

  "scripts": {
    "test": "./node_modules/.bin/wdio ./wdio.conf.js"
  },

![image](https://user-images.githubusercontent.com/65136873/108602556-445f3e00-7381-11eb-9cde-0e1a79aeabc2.png)

**Comment by jpott77** [comment]
@smrn-qa @thocego 

Replace line 7 in your package.json with "test":"wdio"

**Comment by DiegoCorredorQA** [comment]
This one worked for me:

"scripts": {
    "test": "wdio wdio.conf.js"
  },
