### ISSUE TITLE
error al ejecutar "npm run test"

### ISSUE THREAD

**Issue by thocego** [jpott77/webdriverio#7]
![image](https://user-images.githubusercontent.com/76695279/108230643-fba04e80-710e-11eb-9f33-70544fbe1a25.png)

**Comment by smrn-qa** [comment]
I had the same issue, but i solved it changing the following:

 "scripts": {
    "test": "./node_modules/.bin/wdio ./wdio.conf.js"
  },

At least that worked for me.

**Comment by saamorin** [comment]
I had the same issue, but i solved it changing the following:

"scripts": {
"test": "./node_modules/.bin/wdio ./wdio.conf.js"
},

At least that worked for me

**Comment by jpott77** [comment]
@thocego This video and the pinned comment should help resolve the error - https://www.youtube.com/watch?v=Xm-q99UPD_0
